/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DonationsRouteImport } from './routes/donations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard.projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardProjectsIndexRouteImport } from './routes/dashboard.projects.index'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard.projects.new'
import { Route as DashboardProjectsPreviewProjectIdRouteImport } from './routes/dashboard.projects.preview.$projectId'
import { Route as DashboardProjectsEditProjectIdRouteImport } from './routes/dashboard.projects.edit.$projectId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DonationsRoute = DonationsRouteImport.update({
  id: '/donations',
  path: '/donations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsIndexRoute = DashboardProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => DashboardProjectsRoute,
} as any)
const DashboardProjectsPreviewProjectIdRoute =
  DashboardProjectsPreviewProjectIdRouteImport.update({
    id: '/preview/$projectId',
    path: '/preview/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)
const DashboardProjectsEditProjectIdRoute =
  DashboardProjectsEditProjectIdRouteImport.update({
    id: '/edit/$projectId',
    path: '/edit/$projectId',
    getParentRoute: () => DashboardProjectsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donations': typeof DonationsRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardProjectsEditProjectIdRoute
  '/dashboard/projects/preview/$projectId': typeof DashboardProjectsPreviewProjectIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/donations': typeof DonationsRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/projects': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardProjectsEditProjectIdRoute
  '/dashboard/projects/preview/$projectId': typeof DashboardProjectsPreviewProjectIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/donations': typeof DonationsRoute
  '/login': typeof LoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/dashboard/projects/': typeof DashboardProjectsIndexRoute
  '/dashboard/projects/edit/$projectId': typeof DashboardProjectsEditProjectIdRoute
  '/dashboard/projects/preview/$projectId': typeof DashboardProjectsPreviewProjectIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/donations'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/'
    | '/dashboard/projects/new'
    | '/dashboard/projects/'
    | '/dashboard/projects/edit/$projectId'
    | '/dashboard/projects/preview/$projectId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/donations'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/dashboard'
    | '/dashboard/projects/new'
    | '/dashboard/projects'
    | '/dashboard/projects/edit/$projectId'
    | '/dashboard/projects/preview/$projectId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/donations'
    | '/login'
    | '/dashboard/admin'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/'
    | '/dashboard/projects/new'
    | '/dashboard/projects/'
    | '/dashboard/projects/edit/$projectId'
    | '/dashboard/projects/preview/$projectId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DonationsRoute: typeof DonationsRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donations': {
      id: '/donations'
      path: '/donations'
      fullPath: '/donations'
      preLoaderRoute: typeof DonationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects/': {
      id: '/dashboard/projects/'
      path: '/'
      fullPath: '/dashboard/projects/'
      preLoaderRoute: typeof DashboardProjectsIndexRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/preview/$projectId': {
      id: '/dashboard/projects/preview/$projectId'
      path: '/preview/$projectId'
      fullPath: '/dashboard/projects/preview/$projectId'
      preLoaderRoute: typeof DashboardProjectsPreviewProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/dashboard/projects/edit/$projectId': {
      id: '/dashboard/projects/edit/$projectId'
      path: '/edit/$projectId'
      fullPath: '/dashboard/projects/edit/$projectId'
      preLoaderRoute: typeof DashboardProjectsEditProjectIdRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
  }
}

interface DashboardProjectsRouteChildren {
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  DashboardProjectsIndexRoute: typeof DashboardProjectsIndexRoute
  DashboardProjectsEditProjectIdRoute: typeof DashboardProjectsEditProjectIdRoute
  DashboardProjectsPreviewProjectIdRoute: typeof DashboardProjectsPreviewProjectIdRoute
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  DashboardProjectsIndexRoute: DashboardProjectsIndexRoute,
  DashboardProjectsEditProjectIdRoute: DashboardProjectsEditProjectIdRoute,
  DashboardProjectsPreviewProjectIdRoute:
    DashboardProjectsPreviewProjectIdRoute,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DonationsRoute: DonationsRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
